feat: get user with token
fintoc-com/slach-rails pull request #41
Opened 2023-01-23 12:48 UTC by oerlandsen

# [Fix]: [Change style prop]

## Description

Se agregó el show del user a partir del token. También se agregó la ruta

## Requirements

None.

## Additional changes

None.

2023-01-23 20:50 UTC, daleal requested changes

2023-01-23 20:50 UTC, daleal commented on app/controllers/api/v1/users_controller.rb
> +  def show_user_token
Este nombre está mal puesto, este método no muestra el token de un usuario. Debería ser algo como `get_user_by_token` o algo así

2023-01-23 20:50 UTC, daleal commented on app/controllers/api/v1/users_controller.rb
> +    if user.present?
Este método está muy nesteado. En general lo que uno debería hacer es descartar lo más rápido posible y retornar, para evitar nestear:

```rb
return render status: :not_found unless user.present?
return render status: :unathorized unless user.update_token_tenerated_at <= 30.minutes.ago

render json { data: Api::V1::UserSerializer.new(user) }
```

2023-01-23 20:50 UTC, daleal commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
Me preocupa un poco que las rutas están empezando a quedar desordenadas y sin mucho sentido. Creo que hay que investigar en general cómo se estructuran las rutas para un recurso cuando ese recurso puede ser conseguido en base a más de un atributo (en nuestro caso puede ser el alias o el token, y en algún thread comentaste que también te gustaría a partir del email)

2023-01-23 21:40 UTC, oerlandsen commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
dale!

2023-01-23 21:47 UTC, oerlandsen commented on app/controllers/api/v1/users_controller.rb
> +  def show_user_token
👍

2023-01-23 21:52 UTC, oerlandsen commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
Pero me queda la duda si hago un solo método de get para el usuario con distintas opciones y query params, porque en el caso del token hay que verificar que exista y siga activo. Me parece más ordenado tenerlo en métodos distintos.

2023-01-24 12:47 UTC, daleal commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
No sé bien cual es el estándar para este tipo de endpoints, creo que hay que leer un poco al respecto. De guata me suena que tener 3 endpoints distintos para buscar un solo modelo es una mala idea y que se hace de otra forma

2023-01-24 14:40 UTC, oerlandsen commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
Por ahora voy a dejar uno para el alias y mail, y otro con el token por temas de orden. Si te parece, cuando integre todo voy a revisar y ver si tener uno queda ordenado y hacer un eventual refactor.

2023-01-24 16:33 UTC, daleal commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
Preferiría que cacharas al tiro cual es la forma en que se debería hacer bien. Este es el tipo de cosas que uno dice "después lo arreglo" y queda una deuda técnica eterna, y creo que hacerlo bien ahora no debería costar más de una hora de buscar en google. Insisto harto con esto porque estoy pensando cómo va a quedar esto en el frontend y va a ser muy complicado de refactorear después, al final nunca lo vamos a hacer.

2023-01-24 19:01 UTC, oerlandsen commented on config/routes.rb
> +      get 'users/token/:id', to: 'users#show_user_token', constraints: { id: /[^\/?]+/ }
entonces se cierra esta pr?

2023-01-25 19:48 UTC, closed without merging